export {
  BACKGROUND_FIELDS,
  CHARACTERISTIC_FIELDS,
  ERAS,
  FORBIDDEN_CARD_FIELDS,
  IDENTITY_FIELDS,
  OCCUPATION_POINT_FORMULAS,
  RULESET,
  SCHEMA_VERSION,
  isOccupationPointFormula,
} from "./characterSchema.js";

export {
  CTHULHU_MYTHOS_NAME,
  RuleError,
  ageBandNote,
  ageMovPenalty,
  attributeMovAdjust,
  build,
  calculateOccupationPoints,
  damageBonus,
  dodgeBase,
  excelCeilingUnit,
  excelInt,
  extremeSuccess,
  hardSuccess,
  hitPoints,
  interestPointsTotal,
  isCthulhuMythosSkill,
  magicPoints,
  majorWoundThreshold,
  movement,
  mythosPointError,
  ownLanguageBase,
  remainingInterestPoints,
  remainingOccupationPoints,
  sanMaximum,
  skillRating,
} from "./coc7.js";

export { validateCharacter } from "./validation.js";
